# Generated by Django 5.2 on 2025-04-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=1, max_digits=2)),
                ('selling_price', models.DecimalField(decimal_places=1, max_digits=2)),
                ('unit_measurement', models.CharField(choices=[('un', 'Unidade'), ('pct', 'Pacote'), ('cx', 'Caixa'), ('dz', 'Dúzia'), ('fd', 'Fardo'), ('lt', 'Lata'), ('rl', 'Rolo'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro')], default='un', max_length=15)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('current_stock', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
